[sdl]
fullscreen=false
windowresolution=1024x768
output=surface

[dosbox]
machine=svga_s3
memsize=16

[cpu]
core=auto
cputype=auto
cycles=max

[render]
scaler=normal2x

[autoexec]
# mount + chay game duoc truyen tu test_dosbox.bat
