#!/usr/bin/env python3
"""Build tools/dialogue_misc_translation_map.json from embedded translation tables."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).resolve().parent / "dialogue_misc_translation_map.json"


def T(translated: str, abbrev: str | None = None) -> dict:
    d: dict = {"translated": translated}
    if abbrev is not None:
        d["abbrev"] = abbrev
    return d


def load_existing() -> dict:
    if OUT.exists():
        with OUT.open(encoding="utf-8") as f:
            return json.load(f)
    return {}


# Dialogue translations keyed by entry id
DIALOGUE: dict[str, dict] = {
    "dialogue_105000": T("Hay mau chiem dan binh", "Hay mau chiem dan binh"),
    "dialogue_105023": T("Them tru thue nang va cac khoan dong gop", "Them tru thue nang"),
    "dialogue_105073": T("Quan ta se nhan vien tro lien tuc", "Vien tro lien tuc"),
    "dialogue_1050A5": T("La nguyen nhan song chet cua tam quan", "Nguyen nhan tam quan"),
    "dialogue_1050E3": T("La chia khoa chien thang", "Chia khoa thang"),
    "dialogue_105101": T("Dam lam nhu vay", "Dam lam vay"),
    "dialogue_105125": T("UNK", "UNK"),
    "dialogue_1051C8": T("Hay chon tuong dan quan xuat chinh", "Chon tuong danh"),
    "dialogue_10528B": T("So luong lua mang theo", "So luong lua"),
    "dialogue_1052CC": T("Hay chon doi van chuyen luong thao", "Chon van luong"),
    "dialogue_1052E8": T("Hay chi dinh tuong huan luyen quan", "Chi dinh tuong"),
    "dialogue_105300": T("Hay chi dinh tuong van bu vat tu", "Chi dinh van bu"),
    "dialogue_10531F": T("Toi da nhieu tuong", "Toi da tuong"),
    "dialogue_105368": T("Hay chon vu khi muon che tao", "Chon vu khi"),
    "dialogue_10537F": T("Tuong chiem binh", "Tuong chiem"),
    "dialogue_105393": T("Tuong thuc hien muu binh", "Tuong muu binh"),
    "dialogue_1053B0": T("Hay chon tuong thuc hien the binh", "Chon the binh"),
    "dialogue_1053CB": T("Chon tuong phan bo lai binh si", "Phan bo binh"),
    "dialogue_105418": T("Khong hieu ly tri tri quoc", "Khong hieu tri quoc"),
    "dialogue_105493": T("Sao co binh thua cho don dien", "Binh thua don dien"),
    "dialogue_1054B7": T("Sau vai nam duoc tram van ho lua", "Tram van ho lua"),
    "dialogue_1054EB": T("Hoa vat kho van xa", "Hoa vat kho van"),
    "dialogue_105519": T("Chac chan du tru quan nhu", "Du tru quan nhu"),
    "dialogue_10554E": T("Khong thong chinh su", "Khong thong chinh"),
    "dialogue_105567": T("Co the tich tru quan luong lon", "Tich tru luong"),
    "dialogue_105593": T("Dung tien thua sua thanh kho giu", "Sua thanh kho"),
    "dialogue_1055BF": T("Ke dich kho long chiem", "Ke dich kho chiem"),
    "dialogue_1055F5": T("Phat tan quan luong cuu dan luu lac", "Cuu dan luu lac"),
    "dialogue_10561B": T("Dan la goc quoc gia", "Dan la goc"),
    "dialogue_105634": T("Nay minh cong vi mot no gian hai dan chung", "No gian hai dan"),
    "dialogue_1056CB": T("Khoc kho dinh tue va thue cho dan", "Dinh tue thue dan"),
    "dialogue_10574B": T("Luc nay mot ho lua den hang chuc van", "Ho lua hang van"),
    "dialogue_105789": T("UNK", "UNK"),
    "dialogue_10579C": T("Tich luong chuan bi chien la thuong sach", "Tich luong chuan bi"),
    "dialogue_1057B1": T("Ban lua de chuan bi quan tu", "Ban lua quan tu"),
    "dialogue_1057C9": T("Chi dung vu khi phong thuong", "Vu khi phong"),
    "dialogue_1057E1": T("Kiem tang anh hung", "Kiem tang anh hung"),
    "dialogue_1057FE": T("Luc nay mua nu la khong sang", "Mua nu khong sang"),
    "dialogue_105813": T("Muon ban xa phai cam nu luyen tap", "Cam nu luyen"),
    "dialogue_105848": T("Va muon lam lan nhu", "Lam lan nhu"),
    "dialogue_10586D": T("Day la ngua Dai Uyen tot cua Tay Vuc", "Ngua Dai Uyen"),
    "dialogue_105899": T("Hay chi dinh tuong khai phat dat", "Chi dinh khai dat"),
    "dialogue_1058CD": T("Tuong phat trien", "Tuong phat trien"),
    "dialogue_1058E5": T("Hay chon tuong tri thuy chong hong", "Chon tri thuy"),
    "dialogue_105904": T("Hay chi dinh tuong day cung tuong", "Chi dinh day tuong"),
    "dialogue_10593D": T("Hay chi dinh tuong thieu sat cuop pha", "Chi dinh thieu sat"),
    "dialogue_105987": T("Dieu chinh thue suat moi la", "Dieu thue moi"),
    "dialogue_10599D": T("Hay chon hang hoa muon giao dich", "Chon hang hoa"),
    "dialogue_1059B8": T("Hay phai tuong mua lua", "Tuong mua lua"),
    "dialogue_1059DD": T("Hay chi dinh tuong mua vu khi tuong", "Mua vu khi"),
    "dialogue_1059F9": T("Hay chi dinh tuong mua nu tien", "Mua nu tien"),
    "dialogue_105A11": T("Hay chi dinh tuong mua ngua", "Mua ngua"),
    "dialogue_105A2C": T("Loai ke xa lan kho thanh cong", "Ke xa lan kho"),
    "dialogue_105A5F": T("Thanh su thi khong co tuong manh tro giup", "Khong tuong manh"),
    "dialogue_105ABF": T("Chu ta dac mang thu mat den", "Mang thu mat"),
    "dialogue_105ADC": T("Dam do lo do thi tran ta", "Do lo do thi"),
    "dialogue_105AFD": T("UNK", "UNK"),
    "dialogue_105B13": T("Ke gian muon chia re hai ta", "Ke gian chia re"),
    "dialogue_105B2D": T("Ta quyet khong lam viec bat nghia nay", "Khong bat nghia"),
    "dialogue_105B8C": T("Chu cong dung mot thu khich dong ho", "Thu khich dong"),
    "dialogue_105BE2": T("Quan than dong long", "Quan than dong long"),
    "dialogue_105C17": T("Ngai co quan chung ngan dam", "Quan chung ngan dam"),
    "dialogue_105C53": T("Ai theo ta o day", "Ai theo ta"),
    "dialogue_105C87": T("Sao lam viec phan chu", "Phan chu"),
    "dialogue_105CA9": T("Tieu ky nay chac bi phat hien", "Bi phat hien"),
    "dialogue_105CDD": T("Ke nay se khien ke tu giet nhau", "Ke tu giet"),
    "dialogue_105D0F": T("Neu thay cho yeu tren thu", "Thay cho yeu"),
    "dialogue_105DC5": T("Rat hay", "Rat hay"),
    "dialogue_105DD3": T("Sao xoa lam roi het", "Xoa lam roi"),
    "dialogue_105DE9": T("UNK", "UNK"),
    "dialogue_105E01": T("Chac la ngai so ta biet chi tiet", "So ta biet"),
    "dialogue_105E55": T("Tieu ky muon lua ta", "Tieu ky lua ta"),
    "dialogue_105E70": T("Du tri da muu", "Du tri da muu"),
    "dialogue_105E87": T("Tru di mot dai hoan trong long", "Tru dai hoan"),
    "dialogue_105EB7": T("Nay mao hiem mang den bao cho tuong", "Bao cho tuong"),
    "dialogue_105EF5": T("Phan tac vo le the", "Phan tac vo le"),
    "dialogue_105F09": T("Den truoc trai", "Den truoc trai"),
    "dialogue_105F20": T("Ta muon ngai lam tien phong", "Lam tien phong"),
    "dialogue_105F31": T("Chua luyen thuan thuc", "Chua luyen"),
    "dialogue_105F4D": T("Neu quan ho luyen thuan", "Quan luyen thuan"),
    "dialogue_105F7B": T("Ta sao trung ke", "Sao trung ke"),
    "dialogue_105FD0": T("Minh cong khong can lo", "Khong can lo"),
    "dialogue_106001": T("Ke nay kho thanh cong", "Kho thanh cong"),
    "dialogue_10601F": T("Co the nhan co pha tuong thanh", "Pha tuong thanh"),
    "dialogue_106041": T("Ke kho nhu khong lua duoc ong", "Kho nhu khong lua"),
    "dialogue_10606D": T("Can mot nguoi lam gia hang cho ta", "Gia hang"),
    "dialogue_10609D": T("Hon la hang de van toan", "Hang de van toan"),
    "dialogue_1060ED": T("Ngai noi loi nay", "Noi loi nay"),
    "dialogue_10612B": T("Nhung bat loi cho quan", "Bat loi quan"),
    "dialogue_10615B": T("Khong xet mat quan vien", "Khong xet mat"),
    "dialogue_10619D": T("Cung la tuong lon mot phuong", "Tuong lon phuong"),
    "dialogue_1061F4": T("Ta tu thuo doc binh thu", "Doc binh thu"),
    "dialogue_106213": T("Nhu tre con mong cha me", "Mong cha me"),
    "dialogue_10623B": T("Neu ngai lap dai cong", "Lap dai cong"),
    "dialogue_106283": T("Dam treu choc ta", "Treu choc ta"),
    "dialogue_1062BB": T("Co dong gi cung bi ong biet", "Ong biet het"),
    "dialogue_1062FD": T("Day la ke phu do chou thao", "Phu do chou"),
    "dialogue_106339": T("Chac khong phuc vu minh cong", "Khong phuc vu"),
    "dialogue_10635B": T("Mang mot tuong lam su", "Tuong lam su"),
    "dialogue_106387": T("Tuong khong binh an", "Khong binh an"),
    "dialogue_106399": T("Nen khong dung tuong gioi quyet tu chien", "Khong quyet tu chien"),
    "dialogue_10645F": T("Theo loi ngai", "Theo loi ngai"),
    "dialogue_10646B": T("Khong the bo roi", "Khong bo roi"),
    "dialogue_106483": T("UNK", "UNK"),
    "dialogue_10649D": T("Chi can mot thu ket noi noi ung", "Thu ket noi ung"),
    "dialogue_1064DD": T("Nay la than phan phan tac", "Than phan phan tac"),
    "dialogue_106537": T("Minh cong neu co hanh dong", "Neu co hanh dong"),
    "dialogue_106567": T("Bi van dai nhuc nha", "Bi nhuc nha"),
    "dialogue_10659B": T("Di nay chac khong thanh", "Khong thanh"),
    "dialogue_1065C1": T("Thay mot sao tuong sap roi", "Sao tuong roi"),
    "dialogue_1065F5": T("UNK", "UNK"),
    "dialogue_106603": T("Ban cung o day", "Ban cung o day"),
    "dialogue_10661B": T("Chung ta theo lenh chu den lay mang ngai", "Lay mang ngai"),
    "dialogue_106647": T("Sao gia mao binh linh o day", "Gia mao binh"),
    "dialogue_106685": T("UNK", "UNK"),
    "dialogue_1066BE": T("UNK", "UNK"),
    "dialogue_1066E8": T("So binh si", "So binh si"),
    "dialogue_106706": T("UNK", "UNK"),
    "dialogue_10671C": T("Trang thai", "Trang thai"),
    "dialogue_106799": T("Ten tai da", "Ten tai da"),
    "dialogue_1067A1": T("So quan chu", "So quan chu"),
    "dialogue_106814": T("Bo cuoc", "Bo cuoc"),
    "dialogue_10681A": T("Quyet dinh", "Quyet dinh"),
    "dialogue_10686E": T("Loai bao vat", "Loai bao"),
    "dialogue_106895": T("Chua lien minh", "Chua lien minh"),
    "dialogue_1068A1": T("Lien minh cong thu", "Cong thu LM"),
    "dialogue_1068C3": T("Nguoi quan ly", "Quan ly"),
    "dialogue_1068FB": T("Chon hai quoc gia thuc hien", "Chon 2 quoc"),
    "dialogue_10691A": T("Hay chon hai tuong lam mat su", "Chon 2 mat su"),
    "dialogue_1069ED": T("Quan huyen khu ho ton lang", "Khu ho ton lang"),
    "dialogue_106A0D": T("Hay chon tuong thuc hien ke nay", "Chon tuong"),
    "dialogue_106BA0": T("Hay chon tuong lam su thuc hien ke", "Tuong lam su"),
    "dialogue_106BCC": T("Gui thu gia den", "Gui thu gia"),
    "dialogue_106C1C": T("Hay chon quan huyen giet nguoi dao", "Giet nguoi dao"),
    "dialogue_106CEB": T("Quan huyen hon nuoc mo ca", "Hon nuoc mo ca"),
    "dialogue_106D09": T("Thuc hien ke hon nuoc mo ca", "Ke hon nuoc"),
    "dialogue_106D4B": T("Hay chon quan huyen pha tuong", "Pha tuong"),
    "dialogue_106DA9": T("Hay chon quan huyen ke kho nhu", "Ke kho nhu"),
    "dialogue_106DC7": T("Tuong", "Tuong"),
    "dialogue_106DCF": T("Thuc hien ke kho nhu", "Ke kho nhu"),
    "dialogue_106E0C": T("Hay chon quan huyen dot luong", "Dot luong"),
    "dialogue_106E4F": T("Thuc hien ke dot luong", "Ke dot luong"),
    "dialogue_106E6D": T("Quan huyen du do hang", "Du do hang"),
    "dialogue_106E8A": T("Hay chon tuong muc tieu du do", "Chon muc tieu"),
    "dialogue_106EA6": T("Hay chon tuong mat su thuc hien ke", "Mat su ke"),
    "dialogue_106EEC": T("Du do hang thanh cong", "Du do OK"),
    "dialogue_106F05": T("Quan huyen ce phan", "Ce phan"),
    "dialogue_106F21": T("Tuong muc tieu ce phan", "Muc tieu CP"),
    "dialogue_106F3D": T("Tuong mat su thuc hien ke", "Mat su ke"),
    "dialogue_106F84": T("Ce phan thanh cong", "Ce phan OK"),
    "dialogue_106F9D": T("Quan huyen am sat", "Am sat"),
    "dialogue_106FB9": T("Tuong muc tieu am sat", "Muc tieu AS"),
    "dialogue_10700C": T("Thuc hien am sat", "Am sat"),
    "dialogue_1070D8": T("Quan huyen do may quan ly", "May quan ly"),
    "dialogue_107100": T("Nguoi nay khong tham tien", "Khong tham tien"),
    "dialogue_10711F": T("Nguoi nay chac se di", "Chac se di"),
    "dialogue_107135": T("Chu ta mang ngan vang tang tuong", "Tang ngan vang"),
    "dialogue_10716D": T("Ta xin ra suc chon ngua", "Ra suc chon ngua"),
    "dialogue_1071B0": T("Nguoi nay nhu Lieu Ha Hue tai the", "Nhu Lieu Ha Hue"),
    "dialogue_1071D3": T("Dang mot my nhan de thu long", "Dang my nhan"),
    "dialogue_107213": T("Tren thien ha khong anh hung khac", "Khong anh hung"),
    "dialogue_107253": T("Chu ta muon giao nu nay lam thi", "Giao nu lam thi"),
    "dialogue_107289": T("Ta se bao on nhu cho ngua", "Bao on cho ngua"),
    "dialogue_1072A7": T("Nhung lo danh ti khong lap", "Lo danh ti"),
    "dialogue_1072D1": T("Ngai muon dung mot con ngua du do", "Ngua du do"),
    "dialogue_1072F5": T("Ngai muon chiem thien ha", "Chiem thien ha"),
    "dialogue_107311": T("Nay co ngua tot mot con", "Ngua tot mot con"),
    "dialogue_107365": T("Se bao on the nao", "Bao on the nao"),
    "dialogue_107381": T("Sao hom nay o duoi ke nhu", "O duoi ke nhu"),
    "dialogue_1073D8": T("Han khong gap chu", "Han khong gap chu"),
    "dialogue_1073E7": T("Chim tot chon cay ma dau", "Chim chon cay"),
    "dialogue_10744B": T("Nhu mia kho gap mua", "Mia gap mua"),
    "dialogue_10748B": T("Chac khong bi lay chuyen", "Khong lay chuyen"),
    "dialogue_1074A5": T("Chac noi duoc", "Chac noi duoc"),
    "dialogue_1074C1": T("Xin tang minh cong", "Tang minh cong"),
    "dialogue_1074E7": T("Ta sao khong het suc phuc vu", "Het suc phuc vu"),
    "dialogue_107533": T("Von noi tieng co doc", "Noi tieng co doc"),
    "dialogue_107560": T("Minh cong nen tu den moi", "Tu den moi"),
    "dialogue_1075A3": T("Ngai la nguoi trung nghia", "Trung nghia"),
    "dialogue_107600": T("Mong ong mo dau va cuu nan", "Mo dau cuu nan"),
    "dialogue_107665": T("Mong ong vi dan chung thien ha", "Vi dan chung"),
    "dialogue_1076B5": T("Han chua gap anh hung", "Chua gap anh hung"),
    "dialogue_1076D5": T("Tuong sao bo ngoc tim da", "Bo ngoc tim da"),
    "dialogue_10770F": T("Chung khan co y kien gi", "Y kien gi"),
    "dialogue_10772D": T("UNK", "UNK"),
    "dialogue_10774B": T("Day la dao thang binh gia", "Dao thang binh"),
    "dialogue_1077F9": T("Thu hai la pha giao", "Pha giao"),
    "dialogue_107825": T("Nen quan khong dinh ma loi toan", "Loi toan"),
    "dialogue_107891": T("Khong biet ke ma biet minh", "Khong biet ke"),
    "dialogue_1078DB": T("Nen tu bao toan ma thang het", "Tu bao thang het"),
    "dialogue_10794D": T("Quan thang tien chien sau moi danh", "Thang tien chien"),
    "dialogue_10799F": T("Quoc gia ma lam vui", "Quoc lam vui"),
    "dialogue_1079C1": T("UNK", "UNK"),
    "dialogue_1079FD": T("Nay thoi tiet mua thu mat", "Mua thu mat"),
    "dialogue_107A4E": T("Mong quan thu nuoi quan", "Thu nuoi quan"),
    "dialogue_107A91": T("Nay ke dich co khe ha", "Ke co khe"),
    "dialogue_107ABB": T("Nay neu tien quan gap", "Tien quan gap"),
    "dialogue_107B05": T("Quan ta la doi quan luyen tap", "Quan luyen tap"),
    "dialogue_107B57": T("Hon nua quan muon hy sinh", "Quan hy sinh"),
    "dialogue_107BF3": T("Nay chi nen tu bin nghi vu", "Tu bin nghi vu"),
    "dialogue_107C4D": T("Day la ke bao quoc", "Ke bao quoc"),
    "dialogue_107C93": T("Tuong van muon lam cuong", "Muon lam cuong"),
    "dialogue_107CED": T("Neu khong xet thoi ma tien", "Khong xet thoi"),
    "dialogue_107D43": T("Ngai nen tu duc an dan", "Tu duc an dan"),
    "dialogue_107D93": T("Hom nay tuong lai muon xuat quan", "Muon xuat quan"),
    "dialogue_107DE1": T("Minh cong vi mot no ma dong quan", "No dong quan"),
    "dialogue_107E3D": T("Tuong khong nen gian ma chien", "Khong gian chien"),
    "dialogue_107E99": T("Ben chau de quan nhieu thi khong du", "Quan nhieu khong du"),
    "dialogue_107F71": T("Nay lai dong binh lam loan dan", "Dong binh loan dan"),
    "dialogue_107FE0": T("Cho co khe moi hanh dong", "Cho co khe"),
    "dialogue_108017": T("Ta muon on dinh lanh tho truoc", "On dinh lanh tho"),
    "dialogue_10804B": T("So dan loan khoi day", "Dan loan khoi day"),
    "dialogue_108079": T("Nen van luong du phong", "Van luong du phong"),
    "dialogue_1080AF": T("Nhung luong thao khong du", "Luong khong du"),
    "dialogue_1080EB": T("Cho binh linh tan ra dong trai", "Tan ra dong trai"),
    "dialogue_108135": T("Ngai nghia duc den bon phuong", "Nghia bon phuong"),
    "dialogue_108177": T("Day la uy luc chu cong", "Uy chu cong"),
    "dialogue_1081B5": T("Bon chau kho luong day lua", "Kho luong day"),
    "dialogue_1081E7": T("Tu than gia quoc tri binh thien ha", "Tu than tri quoc"),
    "dialogue_108228": T("Chung ta de la ke ngu don", "Ke ngu don"),
    "dialogue_108253": T("Khong co loi hay de dang chu cong", "Khong loi hay"),
    "dialogue_108285": T("Khong phai ke vo muu biet", "Khong vo muu"),
    "dialogue_1082B8": T("Chung khan trinh bay y kien", "Trinh bay y kien"),
    "dialogue_1082EF": T("Luu Bi la anh hung", "Luu Bi anh hung"),
    "dialogue_108311": T("Sao phai tri hoan", "Phai tri hoan"),
    "dialogue_108347": T("Sau se chet tay tieu nhan", "Chet tieu nhan"),
    "dialogue_10838D": T("Dien Phong cung ma pham thuong", "Dien Phong cung"),
    "dialogue_108437": T("Cong Lo nhu xuong trong mo", "Cong Lo xuong"),
    "dialogue_108453": T("Lu Bo nhu cho soi", "Lu Bo cho soi"),
    "dialogue_10847F": T("Chu cong neu khong thua de diet", "Khong thua diet"),
    "dialogue_1084DC": T("Danh tac Han phu vuong that", "Danh tac Han"),
    "dialogue_10850F": T("So mat nghia voi thien ha", "Mat nghia"),
    "dialogue_10853B": T("Hang ngay luyen binh", "Luyen binh"),
    "dialogue_10857D": T("Chu cong khoi nghia an thien ha", "Khoi nghia an"),
    "dialogue_1085B7": T("Cac ngai tri hoan quan tam", "Tri hoan quan"),
    "dialogue_1085F6": T("Cho luc long day du", "Long day du"),
    "dialogue_108627": T("Huyen Duc von noi tieng anh hung", "Huyen Duc anh hung"),
    "dialogue_1086B7": T("Khac voi ke bi quan truoc", "Khac bi quan"),
    "dialogue_108721": T("Chac bo luong cuong ngua don vuong", "Bo luong don vuong"),
    "dialogue_1087A5": T("Ton Sach o Giang Dong theo song", "Ton Sach song"),
    "dialogue_1087F9": T("Nay nhu ho chiem Ky Chau", "Ho chiem Ky"),
    "dialogue_108849": T("Lam ke dich bat loi", "Ke dich bat loi"),
    "dialogue_1088B3": T("Lai co vien tuong Cuong", "Vien Cuong"),
    "dialogue_1088DB": T("Hon nua co quan Cuong", "Quan Cuong"),
    "dialogue_108905": T("Nguoi Kinh Chau goi mot trong Bat Tuan", "Bat Tuan Kinh"),
    "dialogue_108963": T("Khong phai ke tham loi bo nghia", "Khong tham loi"),
    "dialogue_1089B3": T("Khong the dong quan lon lai", "Khong dong quan"),
    "dialogue_108A17": T("Moi co the tien quan dai", "Tien quan dai"),
    "dialogue_108A3F": T("Khong the khe dich", "Khong khe dich"),
    "dialogue_108A63": T("Nhu ho them can", "Ho them can"),
    "dialogue_108A8D": T("Ngai dung binh gioi", "Dung binh gioi"),
    "dialogue_108AB9": T("Khong the chien", "Khong chien"),
    "dialogue_108AD9": T("Hon la cau hoa an dan", "Cau hoa an dan"),
    "dialogue_108B15": T("Ke vo dung", "Vo dung"),
    "dialogue_108B30": T("Hon nua tri chinh nhan la goc", "Tri chinh nhan goc"),
    "dialogue_108B5D": T("Thong binh phap", "Thong binh phap"),
    "dialogue_108B95": T("Ta biet ong thuong bat man", "Thuong bat man"),
    "dialogue_108BD7": T("Khong cho doc chuoc quyen", "Khong doc quyen"),
    "dialogue_108BF9": T("Sao khong moi den", "Khong moi den"),
    "dialogue_108C19": T("Tron loan an minh o day", "An minh o day"),
    "dialogue_108C50": T("Tuong ta deu ve chu cong", "Deu ve chu cong"),
    "dialogue_108C73": T("Chac hy sinh bao on tri ngai", "Hy sinh bao on"),
    "dialogue_108CA4": T("Xong dau rot mau khong lui", "Xong dau rot mau"),
    "dialogue_108CDD": T("Anh tai thien ha ve chu cong", "Anh tai ve chu"),
    "dialogue_108D27": T("Neu lam le tam cung tim tai", "Tam cung tim tai"),
    "dialogue_108D60": T("Dong que khong tai dung", "Dong que khong tai"),
    "dialogue_108D89": T("Chu cong nen xet nhan dung tai", "Xet nhan dung tai"),
    "dialogue_108DC1": T("Chu cong thuong phat ro", "Thuong phat ro"),
    "dialogue_108DE3": T("Thuong hu thi quan oan", "Thuong hu quan oan"),
    "dialogue_108E03": T("La phap dien thien cu ac", "Dien thien cu ac"),
    "dialogue_108E3B": T("Hy sinh tan toan", "Hy sinh tan toan"),
    "dialogue_108E57": T("Khong vi mot nu ma hy sinh", "Khong vi mot nu"),
    "dialogue_108E7D": T("La tam phuc tuong manh chu cong", "Tam phuc tuong"),
    "dialogue_108EDA": T("Van tang ngua quy", "Van tang ngua"),
    "dialogue_108F15": T("Chu cong sao tang bao vat", "Sao tang bao"),
    "dialogue_108F3B": T("Dung si biet hy sinh vi gi", "Biet hy sinh"),
    "dialogue_108F5B": T("Giao cong chua cho nguoi nay", "Giao cong chua"),
    "dialogue_108F88": T("La anh tuong thoi dai", "Anh tuong thoi"),
    "dialogue_108FC1": T("Nguoi nay chac sinh long phan", "Sinh long phan"),
    "dialogue_108FDD": T("La minh chau nem toi", "Minh chau nem"),
    "dialogue_10900B": T("La tai an bang dinh quoc", "An bang dinh"),
    "dialogue_10902F": T("Minh cong neu truc xuat", "Neu truc xuat"),
    "dialogue_109061": T("UNK", "UNK"),
    "dialogue_10908B": T("Hon nua viec chua ro", "Viec chua ro"),
    "dialogue_1090B9": T("UNK", "UNK"),
    "dialogue_1090E5": T("Neu khong diet tan goc", "Khong diet goc"),
    "dialogue_109108": T("Hom nay khong giet tac", "Khong giet tac"),
    "dialogue_109121": T("Giu ngai lam gi", "Giu lam gi"),
    "dialogue_109143": T("UNK", "UNK"),
    "dialogue_109165": T("Cach trieu chieu", "Trieu chieu"),
    "dialogue_10918F": T("Quan huyen trieu chieu tuong", "Trieu tuong"),
    "dialogue_1091AC": T("Khong tuong tai da", "Khong tuong da"),
    "dialogue_1091BF": T("Tuong trieu chieu", "Tuong trieu"),
    "dialogue_1091D5": T("UNK", "UNK"),
    "dialogue_1091EF": T("Hay nhap so vang tang", "Nhap so vang"),
    "dialogue_1092AA": T("Quyet khong phuc vu", "Khong phuc vu"),
    "dialogue_1092CC": T("Trieu chieu that bai", "Trieu that bai"),
    "dialogue_109317": T("Dung sac du do", "Dung sac"),
    "dialogue_1093B4": T("Trong quan khong co ma quy", "Khong ma quy"),
    "dialogue_109474": T("Chu cong khong co bao vat", "Khong bao vat"),
    "dialogue_10948F": T("Hay chon bao vat tang", "Chon bao tang"),
    "dialogue_10958C": T("Khong tuong hop de trieu", "Khong tuong hop"),
    "dialogue_1095BC": T("Thuyet phuc bang dai nghia", "Thuyet dai nghia"),
    "dialogue_109650": T("Hay chon quan thay quan chuc", "Chon quan"),
    "dialogue_109668": T("Hay chon tuong thay quan chuc", "Chon tuong"),
    "dialogue_109684": T("Hay chon quan chuc muon thay", "Chon quan chuc"),
    "dialogue_1096D8": T("Tong tuong chua du sau nguoi", "Chua du 6 tuong"),
    "dialogue_109704": T("Hay chon chu de hoi nghi", "Chon chu de"),
    "dialogue_10971D": T("UNK", "UNK"),
    "dialogue_109738": T("Ke nay khong thuc hien duoc", "Khong thuc hien"),
    "dialogue_10978D": T("UNK", "UNK"),
    "dialogue_109796": T("Hay chon quoc gia thao luan", "Chon quoc gia"),
    "dialogue_10989C": T("Hay chon quan huyen thuong tuong", "Chon quan thuong"),
    "dialogue_1098CE": T("Hay nhap so vang thuong", "Nhap vang thuong"),
    "dialogue_1099E0": T("Chu cong khong con cong chua", "Khong cong chua"),
    "dialogue_109A1A": T("Hay chon tuong cuoi cong chua", "Chon tuong cuoi"),
    "dialogue_109A37": T("Giao cong chua cho", "Giao cong chua"),
    "dialogue_109A54": T("Hay chon cach xu phat", "Chon xu phat"),
    "dialogue_109A67": T("Hay chon quan huyen xu tuong", "Chon quan xu"),
    "dialogue_109A9D": T("Hay chon bao vat tru", "Chon bao tru"),
    "dialogue_109AF0": T("Hay chon quan huyen truc xuat", "Chon truc xuat"),
    "dialogue_109B0C": T("Hay chon tuong truc xuat", "Chon tuong truc"),
    "dialogue_109B32": T("Quan huyen truc dau tuong", "Truc dau tuong"),
    "dialogue_109B4D": T("UNK", "UNK"),
    "dialogue_109B80": T("Da bi truc dau thi chung", "Bi truc dau"),
    "dialogue_109BC4": T("La ca trong dao ta", "Ca trong dao"),
    "dialogue_109BFB": T("Hai nuoc hop thi co loi", "Hop co loi"),
    "dialogue_109C5F": T("May man khong lam mat mang", "Khong mat mang"),
    "dialogue_109C74": T("Am muu ta rat gan", "Am muu gan"),
    "dialogue_109C8B": T("Tin nghia noi tieng chu hau", "Tin nghia chu hau"),
    "dialogue_109CD7": T("Minh cong nen tan cong gap", "Tan cong gap"),
    "dialogue_109CF9": T("La uy luc chu cong", "Uy chu cong"),
    "dialogue_109D11": T("Loai bo tin nghia", "Bo tin nghia"),
    "dialogue_109D31": T("Thieu mot nguoi bien thien", "Thieu bien thien"),
    "dialogue_109D7B": T("Khong thuyet phuc duoc", "Khong thuyet phuc"),
    "dialogue_109D95": T("Mang mot tuong dan quan tro", "Tuong dan tro"),
    "dialogue_109DAF": T("Thay nuoc lang co nan", "Lang co nan"),
    "dialogue_109DD5": T("Nuoc ta tich o lau", "Tich o lau"),
    "dialogue_109E0D": T("Giup vang va luong", "Giup vang luong"),
    "dialogue_109E21": T("Khong muon cho luong", "Khong cho luong"),
    "dialogue_109E37": T("Mang tuong dan quan pha la thuong", "Dan quan pha"),
    "dialogue_109E75": T("Chu hau khong dam nhin ta", "Khong dam nhin"),
    "dialogue_109EA4": T("Vui ve chap nhan", "Vui chap nhan"),
    "dialogue_109EB1": T("Chu cong sao khong danh", "Sao khong danh"),
    "dialogue_109EDD": T("Can gi cho luong ke", "Can gi cho"),
    "dialogue_109F0D": T("Hon la dung ke nhuu nhu", "Ke nhuu nhu"),
    "dialogue_109F62": T("Chon ngay hoi le", "Chon ngay hoi"),
    "dialogue_109F7B": T("Khong xung mong chu cong", "Khong xung mong"),
    "dialogue_109F93": T("Hon la dung phap nhuu nhu", "Phap nhuu nhu"),
    "dialogue_109FC7": T("Nay nhu chim bi ban", "Nhu chim ban"),
    "dialogue_109FF9": T("Qua nhu mong muon", "Nhu mong"),
    "dialogue_10A011": T("UNK", "UNK"),
    "dialogue_10A047": T("Tot cua tot", "Tot cua tot"),
    "dialogue_10A065": T("De cuu mang dan mot quan", "Cuu dan quan"),
    "dialogue_10A0A1": T("Hai quan chi gap tren chien truong", "Gap chien truong"),
    "dialogue_10A0CF": T("Quyet khong hoa", "Khong hoa"),
    "dialogue_10A0E7": T("Nen gia lenh Thien tu", "Gia lenh Thien tu"),
    "dialogue_10A13B": T("Lien hai ben ngung chien", "Ngung chien"),
    "dialogue_10A167": T("Khong nghe khuyen", "Khong nghe"),
    "dialogue_10A183": T("Bo mot ke vo muu", "Bo vo muu"),
    "dialogue_10A1C9": T("Tra ve nuoc ta", "Tra ve nuoc"),
    "dialogue_10A1DF": T("Khong the chuoc", "Khong chuoc"),
    "dialogue_10A201": T("Quoc gia lien minh", "Quoc lien minh"),
    "dialogue_10A219": T("Tuong lam su", "Tuong lam su"),
    "dialogue_10A238": T("Hay nhap thoi han lien minh", "Nhap thoi han"),
    "dialogue_10A311": T("UNK", "UNK"),
    "dialogue_10A35C": T("Hay chon quan huyen hop tan", "Hop tan"),
    "dialogue_10A3E0": T("Hay chon vat tu vien tro", "Chon vat tu"),
    "dialogue_10A3F8": T("Hay nhap vien tro", "Nhap vien tro"),
    "dialogue_10A4C4": T("Hay chon quoc gia lien hon", "Chon lien hon"),
    "dialogue_10A587": T("Quoc gia tien cong", "Tien cong"),
    "dialogue_10A5A0": T("Hay chon vat tu tien cong", "Vat tien cong"),
    "dialogue_10A611": T("UNK", "UNK"),
    "dialogue_10A67C": T("Hay chon quoc gia ep buoc", "Chon ep buoc"),
    "dialogue_10A691": T("Vat tu yeu cau", "Vat yeu cau"),
    "dialogue_10A6AB": T("Ep yeu cau", "Ep yeu cau"),
    "dialogue_10A7E0": T("Hay chon quoc gia hang phuc", "Chon hang phuc"),
    "dialogue_10A8E5": T("UNK", "UNK"),
    "dialogue_10A9B8": T("Uy tin quoc gia ton hai", "Uy tin ton hai"),
    "dialogue_10A9D4": T("Hay chon quoc gia trao tu", "Chon trao tu"),
    "dialogue_10AA0C": T("Hay chon tuong tu bin tra", "Chon tu tra"),
    "dialogue_10AA27": T("Hay chon dieu kien trao doi", "Dieu kien trao"),
    "dialogue_10AA5D": T("Tuong tu bin dich tra", "Tu bin dich"),
    "dialogue_10AA7D": T("UNK", "UNK"),
    "dialogue_10AB84": T("Co quyet che tao khong", "Quyet che tao"),
    "dialogue_10AC15": T("Co quyet thuc hien khong", "Quyet thuc hien"),
    "dialogue_10AC3E": T("Kho luong trong rong", "Kho rong"),
    "dialogue_10AD37": T("Hay chon vu khi muon mua", "Chon mua VK"),
    "dialogue_10ADE8": T("Khong du vang mua nu tien", "Khong du vang"),
    "dialogue_10AE5C": T("Khong du vang mua ngua", "Khong du vang"),
    "dialogue_10AE8C": T("Khong con thanh nien tot", "Khong thanh nien"),
    "dialogue_10AEF0": T("tan binh", "tan binh"),
    "dialogue_10AF10": T("Co quyet chiem binh khong", "Quyet chiem"),
    "dialogue_10AF2D": T("UNK", "UNK"),
    "dialogue_10AF9A": T("Chiem binh", "Chiem binh"),
    "dialogue_10AFBC": T("Co quyet muu binh khong", "Quyet muu"),
    "dialogue_10B025": T("Ngua", "Ngua"),
    "dialogue_10B03C": T("Nu binh", "Nu binh"),
    "dialogue_10B046": T("Lien nu", "Lien nu"),
    "dialogue_10B052": T("Hay chon loai binh tai bien", "Chon loai binh"),
    "dialogue_10B06C": T("Hay nhap so binh tai bien", "Nhap so binh"),
    "dialogue_10B0A1": T("Hay chon quan huyen dich", "Chon quan dich"),
    "dialogue_10B0C4": T("Hay chon muc van bu", "Chon van bu"),
    "dialogue_10B0F1": T("UNK", "UNK"),
    "dialogue_10B111": T("Khong co vang trong", "Khong vang"),
    "dialogue_10B128": T("Nhap van chuyen", "Nhap van"),
    "dialogue_10B179": T("Khong co ngua trong", "Khong ngua"),
    "dialogue_10B18D": T("Nhap van chuyen", "Nhap van"),
    "dialogue_10B1C1": T("UNK", "UNK"),
    "dialogue_10B1E4": T("Khong co lien nu", "Khong lien nu"),
    "dialogue_10B215": T("Khong co phat da xe", "Khong phat da"),
    "dialogue_10B24B": T("Khong co xe xung", "Khong xung xe"),
    "dialogue_10B2B1": T("Khong co can lan", "Khong can lan"),
    "dialogue_10B2E5": T("Khong co nguyen vu", "Khong nguyen vu"),
    "dialogue_10B394": T("Hon la theo minh chu khac", "Theo minh khac"),
    "dialogue_10B3C9": T("Nghe tieng dung truong tuong", "Dung truong tuong"),
    "dialogue_10B417": T("Chua gap ai nhu minh cong", "Chua gap ai"),
    "dialogue_10B467": T("Minh cong chi tai nap si", "Chi tai nap si"),
    "dialogue_10B484": T("Mua lon", "Mua lon"),
    "dialogue_10B499": T("UNK", "UNK"),
    "dialogue_10B4B1": T("Vi ly", "Vi ly"),
    "dialogue_10B4B9": T("UNK", "UNK"),
    "dialogue_10B4C3": T("Giam mieng", "Giam mieng"),
    "dialogue_10B4CB": T("Giam nghiep", "Giam nghiep"),
    "dialogue_10B4D3": T("UNK", "UNK"),
    "dialogue_10B4E3": T("Si khi tang", "Si khi tang"),
    "dialogue_10B4F3": T("Vang", "Vang"),
    "dialogue_10B4FC": T("Tang luong", "Tang luong"),
    "dialogue_10B514": T("Bao vat", "Bao vat"),
    "dialogue_10B533": T("Dai nghiep thanh cong mong xuan", "Mong xuan"),
    "dialogue_10B553": T("Ngai thong nhat thien ha", "Thong nhat"),
    "dialogue_10B7FA": T("Quan xay bao loan", "Bao loan"),
    "dialogue_10B81F": T("Tri do giam", "Tri do giam"),
    "dialogue_10B9DC": T("Khong co ton hai", "Khong ton hai"),
    "dialogue_10BAB7": T("Chi tieu luong quan quan", "Chi luong quan"),
    "dialogue_10BAD4": T("Tri do la", "Tri do la"),
    "dialogue_10BB3B": T("Don dien thieu hut", "Don thieu hut"),
    "dialogue_10BB58": T("Don dien binh an", "Don binh an"),
    "dialogue_10BB72": T("Don dien thu hoach", "Don thu hoach"),
    "dialogue_10BC1C": T("Quan thu tang", "Thu tang"),
    "dialogue_10BC88": T("Do huan luyen tang", "Huan tang"),
    "dialogue_10BCB2": T("Van chuyen tren duong", "Van chuyen"),
    "dialogue_10BD48": T("Moi duoc tan binh", "Tan binh"),
    "dialogue_10BDF4": T("Hoan thanh", "Hoan thanh"),
    "dialogue_10BE06": T("UNK", "UNK"),
    "dialogue_10BE50": T("Nong nghiep tang", "Nong tang"),
    "dialogue_10BE62": T("Gat nuoc ma gieo", "Gat nuoc gieo"),
    "dialogue_10BE77": T("Ket thuc don dien", "Ket don dien"),
    "dialogue_10BEA0": T("Thuong nghiep tang", "Thuong tang"),
    "dialogue_10BECC": T("Chong hong tang", "Chong hong"),
    "dialogue_10BF5C": T("Gui cho quan chu", "Gui quan chu"),
    "dialogue_10BF75": T("UNK", "UNK"),
    "dialogue_10BFAE": T("Kho lua tang", "Kho tang"),
    "dialogue_10BFC0": T("Lua giam", "Lua giam"),
    "dialogue_10BFFB": T("Da mua nu tien", "Mua nu tien"),
    "dialogue_10C00C": T("Da mua ngua tot", "Mua ngua tot"),
    "dialogue_10C234": T("Ha a", "Ha a"),
    "dialogue_10C23C": T("Neu bo kiem ngay", "Bo kiem ngay"),
    "dialogue_10C274": T("Day la y troi", "Y troi"),
    "dialogue_10C28F": T("Dam danh 300 hoi", "300 hoi"),
    "dialogue_10C2B3": T("Ngai chi co tai nay", "Chi co tai nay"),
    "dialogue_10C2DF": T("Khong lay dau ngai", "Khong lay dau"),
    "dialogue_10C321": T("Ky thua nhan", "Ky thua"),
    "dialogue_10C33C": T("Muon di", "Muon di"),
    "dialogue_10C345": T("Ta mot ten", "Mot ten"),
    "dialogue_10C353": T("Khong biet la ke", "Khong biet ke"),
    "dialogue_10C451": T("Phai vay", "Phai vay"),
    "dialogue_10C45B": T("Dam xam bien gioi", "Xam bien gioi"),
    "dialogue_10C473": T("Den lay dau ngai", "Lay dau ngai"),
    "dialogue_10C483": T("UNK", "UNK"),
    "dialogue_10C48F": T("Bao ten truoc", "Bao ten"),
    "dialogue_10C4C5": T("Tra but", "Tra but"),
    "dialogue_10C4D3": T("O day", "O day"),
    "dialogue_10C4DD": T("Bi danh lua", "Bi danh lua"),
    "dialogue_10C4E9": T("Ngua bi troi", "Ngua bi troi"),
    "dialogue_10C4FB": T("Tuong vo danh", "Vo danh"),
    "dialogue_10C515": T("Van co chap ngo", "Van co chap"),
    "dialogue_10C533": T("Sao noi bao", "Sao noi bao"),
    "dialogue_10C549": T("Dam noi loan", "Dam noi loan"),
    "dialogue_10C564": T("Ke tro ac", "Ke tro ac"),
    "dialogue_10C57C": T("Loai chuot nhat", "Chuot nhat"),
    "dialogue_10C594": T("Phan tac hang ha", "Phan tac hang"),
    "dialogue_10C5A3": T("Sao khong hang som", "Khong hang som"),
    "dialogue_10C5B9": T("UNK", "UNK"),
    "dialogue_10C5CC": T("Ke phu dung cuong", "Phu dung cuong"),
    "dialogue_10C5DB": T("UNK", "UNK"),
    "dialogue_10C600": T("Ta quyet giet ngai", "Quyet giet"),
    "dialogue_10C60B": T("Co gi ke", "Co gi ke"),
    "dialogue_10C621": T("UNK", "UNK"),
    "dialogue_10C634": T("O dau", "O dau"),
    "dialogue_10C765": T("Chay mat", "Chay mat"),
    "dialogue_10C790": T("Chi cong chet som", "Chet som"),
    "dialogue_10C7C7": T("Bi kinh hoang", "Bi kinh hoang"),
    "dialogue_10C984": T("Ca toc mai vao lich su", "Mai vao lich su"),
    "dialogue_10CBBF": T("Bi khich dong phan", "Bi khich phan"),
    "dialogue_10CF4D": T("Hung 11", "Hung 11"),
    "dialogue_10CF55": T("Muoi hai", "12"),
    "dialogue_10CF5D": T("Thuong tinh", "Thuong tinh"),
    "dialogue_10CF73": T("UNK", "UNK"),
    "dialogue_10CF79": T("Tau bac", "Tau bac"),
    "dialogue_10CF8C": T("Dong nam", "Dong nam"),
    "dialogue_10CF97": T("Viec ngai hua voi chu ta", "Viec hua chu"),
    "dialogue_10CFC5": T("Ai theo ta cung chet", "Cung chet"),
    "dialogue_10D033": T("Anh hung bon phuong cung tao dai nghiep", "Cung tao nghiep"),
    "dialogue_10D0B3": T("Nhu tan may thay troi", "Tan may thay troi"),
    "dialogue_10D0F4": T("Ai dam quyet tu voi ta", "Dare quyet tu"),
    "dialogue_10D107": T("Den lay mang ngai", "Lay mang"),
    "dialogue_10D117": T("Khong xung giao thu", "Khong xung"),
    "dialogue_10D131": T("Dai ngu", "Dai ngu"),
    "dialogue_10D192": T("Rut lui toan quan", "Rut toan quan"),
    "dialogue_10D1AB": T("UNK", "UNK"),
    "dialogue_10D1B5": T("UNK", "UNK"),
    "dialogue_10D1C2": T("UNK", "UNK"),
    "dialogue_10D1F4": T("Khong the nghi duong", "Khong nghi duong"),
    "dialogue_10D274": T("Khong the khich si khi", "Khong khich"),
    "dialogue_10D375": T("Vi tri bo doi", "Vi tri doi"),
    "dialogue_10D38B": T("Vi tri cong thanh", "Vi tri cong"),
    "dialogue_10D3C8": T("Vat tu", "Vat tu"),
    "dialogue_10D3E8": T("Tran hinh", "Tran hinh"),
    "dialogue_10D42F": T("UNK", "UNK"),
    "dialogue_10D437": T("UNK", "UNK"),
    "dialogue_10D4A3": T("Binh chay chet het", "Binh chet het"),
    "dialogue_10D50B": T("Binh chay het", "Binh chay het"),
    "dialogue_10D5FF": T("Leo tuong cong thanh", "Leo tuong"),
    "dialogue_10D611": T("Dung van ti leo tuong", "Van ti leo"),
    "dialogue_10D641": T("Tan cong doi dich lien", "Tan cong lien"),
    "dialogue_10D65F": T("Hay chon doi dich tan cong", "Chon doi dich"),
    "dialogue_10D677": T("Hay chon doi dich ban", "Chon doi ban"),
    "dialogue_10D7A1": T("Ke hoa tan that bai", "Hoa tan that"),
    "dialogue_10D918": T("Quan da toan quan phuc", "Toan quan phuc"),
    "dialogue_10D973": T("Xe phat da bi pha", "Phat da pha"),
    "dialogue_10D98B": T("Xe xung bi pha", "Xung xe pha"),
    "dialogue_10D9A2": T("Van ti bi pha", "Van ti pha"),
    "dialogue_10D9BC": T("Can lan bi pha", "Can lan pha"),
    "dialogue_10D9D1": T("UNK", "UNK"),
    "dialogue_10D9E5": T("Nha pai bi pha", "Nha pai pha"),
    "dialogue_10D9F9": T("Xa le bi pha", "Xa le pha"),
    "dialogue_10DA9F": T("Ce phan du do hang", "Ce phan du do"),
    "dialogue_10DAD5": T("Ke nay can vang", "Can vang"),
    "dialogue_10DAF8": T("Quan tu khong du", "Quan tu khong du"),
    "dialogue_10DB15": T("Can vat lieu vang", "Can vat lieu"),
    "dialogue_10DB80": T("Dot luong cuop luong", "Dot cuop luong"),
    "dialogue_10DBC7": T("Ke moai thanh cong", "Ke thanh cong"),
    "dialogue_10DBEF": T("Ke dot luong bi phat", "Dot luong phat"),
    "dialogue_10DC17": T("Cho gian xam tham", "Gian xam tham"),
    "dialogue_10DC43": T("Truyen tin ac", "Truyen tin ac"),
    "dialogue_10DC68": T("Tin ac trong dich trai", "Tin ac dich"),
    "dialogue_10DD50": T("Mat tham thu tin dich", "Mat tham thu"),
    "dialogue_10DD6D": T("UNK", "UNK"),
    "dialogue_10DDDB": T("UNK", "UNK"),
    "dialogue_10DE14": T("Tran hinh bo doi", "Tran hinh doi"),
    "dialogue_10DE70": T("Quyet truc dau khong", "Quyet truc dau"),
    "dialogue_10DE83": T("Bi giam trong nguc", "Bi giam nguc"),
    "dialogue_10DE98": T("Quyet tha khong", "Quyet tha"),
    "dialogue_10DEAB": T("Da duoc tha", "Da tha"),
    "dialogue_10DEBA": T("Bi truc dau thi chung", "Truc dau thi"),
}

# Missing misc entries
MISC_EXTRA: dict[str, dict] = {
    "misc_0FAFF1": T("Dao kiem", "Dao kiem"),
    "misc_0FF27D": T("Cong To", "Cong To"),
    "misc_1012C1": T("UNK", "UNK"),
    "misc_1018C7": T("UNK", "UNK"),
    "misc_1019D5": T("UNK", "UNK"),
    "misc_101BA9": T("UNK", "UNK"),
    "misc_101E91": T("UNK", "UNK"),
}

# Fix misc bio with diacritics
FIXES = {
    "misc_0FF4A8": T(
        "Co dong mach nha Han nen lap chi phuc hung Han that",
        "Co dong mach Han lap chi phuc hung Han that",
    ),
}


def main() -> None:
    merged = load_existing()
    merged.update(DIALOGUE)
    merged.update(MISC_EXTRA)
    merged.update(FIXES)
    with OUT.open("w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print(f"Wrote {len(merged)} entries to {OUT}")
    print(f"Dialogue: {len(DIALOGUE)}, misc extra: {len(MISC_EXTRA)}")


if __name__ == "__main__":
    main()
